apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  clusterIP: None    
  ports:
    - port: 2181

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  clusterIP: None
  selector:
    app: kafka
  clusterIP: None    
  ports:
    - port: 9092

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-service
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.3.5
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.3.5
          ports:
            - containerPort: 9092
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service.default.svc.cluster.local:2181"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka-service.default.svc.cluster.local:9092"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms512m -Xmx512m"
            - name: KAFKA_NUM_PARTITIONS
              value: "4"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
          command:
            - sh
            - -c
            - "export KAFKA_BROKER_ID=`hostname | awk -F '-' '{print $2}'` && /etc/confluent/docker/run"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
